version: '3.8'

services:
  bot:
    build: .
    container_name: gentle-man-tg-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://botuser:botpass@postgres:5432/gentle_man_tg_bot
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot-network

  postgres:
    image: postgres:15-alpine
    container_name: gentle-man-tg-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: gentle_man_tg_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botuser -d gentle_man_tg_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot-network

volumes:
  postgres-data:

networks:
  bot-network:
    driver: bridge